[package]
name = "nes-tcp-gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nes-tcp-gen"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "signal", "time"] }
clap = { version = "4", features = ["derive"] }
itoa = "1"

[profile.release]
lto = "thin"
codegen-units = 1
